---
- name: Create consul group
  ansible.builtin.group:
    name: consul
    system: true
    state: present

- name: Create consul user
  ansible.builtin.user:
    name: consul
    system: true
    shell: "/sbin/nologin"
    group: consul
    create_home: false

- name: Create consul data directory
  ansible.builtin.file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: 0775

- name: Create consul configuration directories
  ansible.builtin.file:
    path: "{{ consul_config_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: 0775
