- name: Ensure unzip is installed
  ansible.builtin.package:
    name:
      - unzip
      - wget
      - chrony
    state: present

- name: Set timezone to Europe/Moscow
  become: true
  community.general.timezone:
    name: Europe/Moscow