---
- name: Include a role from a collection
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: consul_ansible_role
        tasks_from: main.yml